### ISSUE TITLE
Keeps saying the file does not exist

### ISSUE THREAD

**Issue by daman20** [daman20/Deduper#1]
I will figure it out in a min, or you can fix it. The problem is in the makehashes.py

**Comment by JackalJoe** [comment]
Just to add to this Unraid container reports a similar error when run this is a clean install of the container

`Commencing Deleting
Traceback (most recent call last):
File "./main.py", line 11, in <module>
deletedupes.main()
File "/deletedupes.py", line 4, in main
with open('hashes.txt', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'hashes.txt'
Commencing Deleting
Traceback (most recent call last):
File "./main.py", line 11, in <module>
deletedupes.main()
File "/deletedupes.py", line 4, in main
with open('hashes.txt', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'hashes.txt'`

**Comment by daman20** [comment]
Just fixed
