### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by horphi0815** [daman20/Deduper#3]
After update still same error

28/06/2021 13:29:46 Pixel format for client 127.0.0.1:
28/06/2021 13:29:46 32 bpp, depth 24, little endian
28/06/2021 13:29:46 true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
28/06/2021 13:29:46 no translation needed
28/06/2021 13:29:46 Enabling NewFBSize protocol extension for client 127.0.0.1
28/06/2021 13:29:46 Enabling full-color cursor updates for client 127.0.0.1
28/06/2021 13:29:46 Using image quality level 6 for client 127.0.0.1
28/06/2021 13:29:46 Using JPEG subsampling 0, Q79 for client 127.0.0.1
28/06/2021 13:29:46 Using compression level 9 for client 127.0.0.1
28/06/2021 13:29:46 Enabling LastRect protocol extension for client 127.0.0.1
28/06/2021 13:29:46 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
28/06/2021 13:29:46 Using tight encoding for client 127.0.0.1
28/06/2021 13:29:47 client_set_net: 127.0.0.1 0.0000
28/06/2021 13:29:47 created xdamage object: 0x40002e
<_io.TextIOWrapper name='/appdata/hashes.json' mode='a+' encoding='UTF-8'>
Traceback (most recent call last):
File "/main.py", line 11, in <module>
myfile.write(json.dumps(hashes))
NameError: name 'hashes' is not defined
[app] starting Deduper...

**Comment by daman20** [comment]
Is that on a clean installation? If not, please try using a clean installation or giving me the steps to replicate on my machine. I can't seem to find why its not working.

**Comment by daman20** [comment]
The problem was it was only scanning sub directories, so it had noting to write to hashes.
